### ISSUE TITLE
launching project failed

### ISSUE THREAD

**Issue by David3310273** [tonyjiafan/nodeJs#2]
Hi, I'm new on node, after I cloned your project and installed nodemon, when I run `npm run dev` in shell, It shows error like below, please tell me how to solve this, thanks!

```
(function (exports, require, module, __filename, __dirname) { .4.15.2@express
                                                                ^^^

SyntaxError: Unexpected number
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/project/nodeJs/app.js:6:18)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by tonyjiafan** [comment]
Hello!
You can try another nodejs version, I'm sorry I have not encountered this problem.
